### ISSUE TITLE
CCXT get_open_position renvoi 'long' au lieu de 'buy'

### ISSUE THREAD

**Issue by mi-molette** [CryptoRobotFr/cBot#4]
La condition suivante ne fonctionne pas :
` if ftx.get_open_position(perpSymbol)[0]['side'] == 'buy':`
A remplacer par 'long' ?
` if ftx.get_open_position(perpSymbol)[0]['side'] == 'long':`

Idem sur les short.

**Comment by CryptoRobotFr** [comment]
Done :)
